name: Deploy Preview

env:
  COMMENT_HEADER: clerk-docs-preview

on:
  pull_request_target:
    types: [labeled]

jobs:
  deploy:
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.event.label.name == 'deploy-preview' }}
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo "${{ toJson(github.event) }}"
      
      - name: Get date
        run: |
          echo "DATE=$(date -u +"%b %d, %Y %I:%M %p")" >> $GITHUB_ENV
    
      - name: Create preview comment
        uses: marocchino/sticky-pull-request-comment@v2.8.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: ${{ env.COMMENT_HEADER}}
          message: |
            Hey @${{ github.event.sender.login }}, your docs preview is currently baking and should be available shortly.

            | Clerk docs preview | Updated |
            | :-- | :-- |
            | :cook: _Baking..._ | ${{ env.DATE }} |
      
      - uses: actions/checkout@v3.5.3

      - name: Checkout fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: checkout-fork
        # if: ${{ github.event.pull_request.head.repo.fork == true }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git_branch=$(git rev-parse --abbrev-ref HEAD)
          git push origin $git_branch
          echo "branch=$git_branch" >> $GITHUB_OUTPUT

      # - name: Checkout application
      #   uses: actions/checkout@v3.5.3
      #   with:
      #     repository: clerkinc/clerk-marketing
      #     token: ${{ secrets.CLERK_GH_TOKEN }}
      #     path: app
      #     ref: production

      - run: npm install --global vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    
      - name: Deploy to Vercel
        id: vercel-deploy
        env:
          DOCS_BRANCH: ${{ steps.checkout-fork.outputs.branch || github.event.pull_request.head.ref }}
        run: |
          # cd app
          git checkout -b preview/$DOCS_BRANCH
          echo "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --build-env DOCS_BRANCH=$DOCS_BRANCH --env DOCS_BRANCH=$DOCS_BRANCH > deployment_url.txt"
          echo "url=$(cat deployment_url.txt)" >> $GITHUB_OUTPUT
          sleep 60
      
      - name: Get date
        run: |
          echo "DATE=$(date -u +"%b %d, %Y %I:%M %p")" >> $GITHUB_ENV
      
      - name: Create preview comment
        uses: marocchino/sticky-pull-request-comment@v2.8.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: ${{ env.COMMENT_HEADER }}
          message: |
            Hey @${{ github.event.sender.login }}, your docs preview is available.

            | Clerk docs preview | Updated |
            | :-- | :-- |
            | :cookie: ${{ steps.vercel-deploy.outputs.url }} | ${{ env.DATE }} |
