name: Deploy Preview

on:
  pull_request_target:
    types: [labeled]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy-preview' }}
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo "${{ toJson(github.event) }}"
      
      - uses: actions/checkout@v3.5.3

      - name: Checkout fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: checkout-fork
        # if: ${{ github.event.pull_request.head.repo.fork == true }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git_branch=$(git rev-parse --abbrev-ref HEAD)
          git push origin $git_branch
          echo "branch=$git_branch" >> $GITHUB_OUTPUT
      - name: Trigger deploy
        env:
          DOCS_BRANCH: ${{ steps.checkout-fork.outputs.branch || github.event.pull_request.head.ref }}
        run: |
          echo "$DOCS_BRANCH"
